# Generated by Django 5.1.1 on 2025-02-14 11:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preliminary_acceptance', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('passport_copy', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('additional_pdf', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('standard', 'Plan Standard'), ('pro', 'Forfait Pro'), ('unlimited', 'Forfait illimité')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('is_popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('mother_email', models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('father_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('father_phone_number', models.CharField(blank=True, help_text="Enter father's phone number without country code", max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 15 digits.', regex='^\\d{9,15}$')])),
                ('mother_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_phone_number', models.CharField(blank=True, help_text="Enter mother's phone number without country code", max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 15 digits.', regex='^\\d{9,15}$')])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to='authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='HousingSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_type', models.CharField(max_length=50)),
                ('preferred_location', models.CharField(max_length=100)),
                ('move_in_date', models.DateField()),
                ('stay_duration', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_needs', models.TextField(blank=True)),
                ('purpose_of_stay', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_occupants', models.IntegerField(blank=True, null=True)),
                ('university_or_workplace', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('rental_contract', models.FileField(blank=True, null=True, upload_to='rental_contracts/')),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housing_searches', to='students.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IrrevocablePaymentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.file')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('carte_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('carte_expiration_date', models.CharField(blank=True, max_length=5, null=True)),
                ('carte_cvv', models.CharField(blank=True, max_length=10, null=True)),
                ('virement_banque_nom', models.CharField(blank=True, max_length=20, null=True)),
                ('virement_iban', models.CharField(blank=True, max_length=20, null=True)),
                ('virement_bic_swift', models.CharField(blank=True, max_length=20, null=True)),
                ('virement_code_bancaire', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_history', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('insurance_duration', models.IntegerField()),
                ('insurance_type', models.CharField(max_length=100)),
                ('beneficiaries', models.TextField()),
                ('insured_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('files', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.file')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_degree_obtained', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=100, null=True)),
                ('desired_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('university_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('accepted_program', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('referred_users', models.ManyToManyField(blank=True, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_country', models.CharField(max_length=100, null=True)),
                ('destination_country', models.CharField(max_length=100, null=True)),
                ('destination_city', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('number_of_passengers', models.IntegerField()),
                ('travel_class', models.CharField(max_length=50)),
                ('preferred_airlines', models.CharField(blank=True, max_length=100)),
                ('special_requests', models.TextField(blank=True)),
                ('files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketing', to='students.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketing_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticketing Service',
                'verbose_name_plural': 'Ticketing Services',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
